
import React, { Component } from 'react';
import { AppRegistry, StyleSheet, Text, View } from 'react-native';
import styles from "../components/styles"

export default class LotsOfStyles extends Component {
    render() {
        return (
            <View style={styles.contentContainer}>
                <Text style={styles.subHeader}>Populations with special considerations for IV thrombolytic administration</Text>
                <Text style={{ fontSize: 14, textAlign: "center" }}>(Adapted from AHA 2016 Scientific Statement and AHA 2018 Guidelines</Text>
                <Text><Text style={styles.boldText}>Pregnancy and Postpartum:</Text><Text style={styles.subText}></Text> Thrombolytic may be considered in pregnancy when the anticipated benefits of treating stroke outweigh the anticipated increased risks of uterine bleeding. Urgent consultation with an obstetrician-gynecologist and potentially a perinatologist to assist with management of the mother and fetus is recommended. The safety and efficacy of thrombolytic in the early postpartum period ({"<"}14 days after delivery) have not been well established, but IV thrombolytic may be considered</Text>
                <Text><Text style={styles.boldText}>Rapidly Improving Symptoms:</Text><Text style={styles.subText}></Text> Thrombolytic is reasonable for patients who present with moderate to severe ischemic stroke and demonstrate early improvement but remain moderately impaired and potentially disabled.  Because time from onset of symptoms to treatment has such a powerful impact on outcome, delaying treatment with thrombolytic to monitor for further improvement is not recommended.</Text>
                <Text><Text style={styles.boldText}>Acute MI or History of Recent MI (Preceding 3 Months):</Text><Text style={styles.subText}></Text> For patients presenting with concurrent acute ischemic stroke and acute MI, treatment with thrombolytic at the dose appropriate for cerebral ischemia, followed by percutaneous coronary angioplasty and stenting if indicated, is reasonable. For patients presenting with acute ischemic stroke and a history of recent MI in the past 3 months, treating the ischemic stroke with thrombolytic is reasonable if the recent MI was non-STEMI or if the recent MI was STEMI involving the right or inferior myocardium, and may be reasonable if the recent MI was STEMI involving the left anterior myocardium.</Text>
                <Text><Text style={styles.boldText}>Pericarditis:</Text><Text style={styles.subText}></Text> For patients with major acute ischemic stroke likely to produce severe disability and acute pericarditis, treatment with thrombolytic may be reasonable; urgent consultation with a cardiologist is recommended in this situation. For patients presenting with moderate acute ischemic stroke likely to produce mild disability and acute pericarditis, treatment with thrombolytic is of uncertain net benefit.</Text>
                <Text><Text style={styles.boldText}>Left-Sided Heart Thrombus:</Text><Text style={styles.subText}></Text>For patients with major acute ischemic stroke likely to produce severe disability and known left atrial or ventricular thrombus, treatment with thrombolytic may be reasonable. For patients presenting with moderate acute ischemic stroke likely to produce mild disability and known left atrial or ventricular thrombus, treatment with thrombolytic is of uncertain net benefit.</Text>
                <Text style={styles.boldText}>Serious Medical Comorbid Illnesses:</Text>
                <Text><Text style={styles.boldText}>-Renal Disease:</Text><Text style={styles.subText}></Text> In patients with end-stage renal disease on hemodialysis and normal aPTT, thrombolytic may be recommended. However, those with elevated aPTT may have elevated risk for hemorrhagic complications.</Text>
                <Text><Text style={styles.boldText}>-Dementia:</Text><Text style={styles.subText}> Patients with dementia may benefit from thrombolytic. Individual considerations such as life expectancy and premorbid level of function are important to determine whether thrombolytic offers clinically meaningful benefit.</Text></Text>
                <Text><Text style={styles.boldText}>-Malignancy:</Text><Text style={styles.subText}> The safety and efficacy of thrombolytic in patients with current malignancy are not well established. Patients with systemic malignancy and reasonable (>6 months) life expectancy may benefit from thrombolytic if other contraindications such as coagulation abnormalities, recent surgery, or systemic bleeding do not coexist.</Text></Text>
                <Text><Text style={styles.boldText}>Preexisting Disability:</Text><Text style={styles.subText}>Preexisting disability does not seem to independently increase the risk of symptomatic ICH after thrombolytic, but it may be associated with less neurological improvement and higher mortality. Thrombolytic therapy with thrombolytic for acute stroke patients with preexisting disability (mRS score ≥2) may be reasonable, but decisions should take into account relevant factors other than mRS (including quality of life, social support, place of residence, need for a caregiver after thrombolytic administration, patients’ and families’ preferences, and goals of care).</Text></Text>
                <Text><Text style={styles.boldText}>Diabetic Hemorrhagic Retinopathy or Other Hemorrhagic Ophthalmological Conditions:</Text><Text style={styles.subText}> Use of thrombolytic in patients presenting with acute ischemic stroke who have a history of diabetic hemorrhagic retinopathy or other hemorrhagic ophthalmic conditions is reasonable to recommend, but the potential increased risk of visual loss should be weighed against the anticipated benefits of reduced stroke-related neurological deficits.</Text></Text>
                <Text><Text style={styles.boldText}>Dural Puncture Within 7 Days:</Text><Text style={styles.subText}>Thrombolytic may be considered.</Text></Text>
                <Text><Text style={styles.boldText}>Aortic Arch Dissection and Cervicocephalic Arterial Dissection, Known or Suspected:</Text><Text style={styles.subText}>Thrombolytic in acute ischemic stroke known or suspected to be associated with aortic arch dissection is not recommended and is potentially harmful. Thrombolytic in acute ischemic stroke known or suspected to be associated with extracranial cervical arterial dissection is reasonably safe within 4.5 hours and is probably recommended. Thrombolytic usefulness and hemorrhagic risk in acute ischemic stroke known or suspected to be associated with intracranial arterial dissection remain unknown, uncertain, and not well established.</Text></Text>
                <Text><Text style={styles.boldText}>Intracardiac Mass:</Text><Text style={styles.subText}> For patients with major acute ischemic stroke likely to produce severe disability and cardiac myxoma or papillary fibroelastoma, treatment with thrombolytic may be reasonable. </Text></Text>
                <Text><Text style={styles.boldText}>Menstruation and Menorrhagia:</Text><Text style={styles.subText}>Because the potential benefits of thrombolytic probably outweigh the risks of serious bleeding in patients with recent or active history of menorrhagia without clinically significant anemia or hypotension, thrombolytic administration may be considered. When there is a history of recent or active vaginal bleeding causing clinically significant anemia, then emergent consultation with a gynecologist is probably indicated before a decision about thrombolytic is made. In patients who are menstruating or have active vaginal bleeding and are treated with thrombolytic, the degree of vaginal bleeding should be monitored for 24 hours after thrombolytic.</Text></Text>
                <Text><Text style={styles.boldText}>Consent for the Incompetent Patient:</Text><Text style={styles.subText}> In an emergency, when the patient is not competent and there is no immediately available legally authorized representative to provide proxy consent, it is recommended to proceed with thrombolytic in an otherwise eligible patient with acute ischemic stroke. Visual displays that convey the benefits and the risks of thrombolytic can be useful to assist with shared decision making and aid in establishing informed consent.</Text></Text>
                <Text><Text style={styles.boldText}>Catheterization Laboratory Environment/Endovascular Complications:</Text><Text style={styles.subText}> Thrombolytic is reasonable for the treatment of acute ischemic stroke complications of cardiac or cerebral angiographic procedures, depending on the usual eligibility criteria.</Text></Text>
                <Text><Text style={styles.boldText}>Psychogenic/Conversion/Malingering Stroke Mimic:</Text><Text style={styles.subText}> The risk of symptomatic intracranial hemorrhage in the stroke mimic population is quite low; thus, starting thrombolytic is probably recommended in preference over delaying treatment to pursue additional diagnostic studies.</Text></Text>
                <Text style={styles.subTextUnderline}>Guideline for sickle cell patients presenting with stroke symptoms</Text>
                <Text><Text style={styles.boldText}>Cerebral microbleeds:</Text><Text style={styles.subText}>Routine use of magnetic resonance imaging (MRI) to exclude cerebral microbleeds before administration of IV thrombolytic is not recommended. If previous MRI has been performed allowing visualization of cerebral microbleeds, IV thrombolytic in patients who have a small number of microbleeds (1-10) is reasonable. In patients who have a high burden of cerebral microbleeds (>10), treatment with IV thrombolytic may be associated with an increased risk of sICH and the benefits of treatment are uncertain. Treatment may be reasonable if there is the potential for substantial benefit.</Text></Text>
                <Text><Text style={styles.boldText}>Sickle Cell Disease:</Text><Text style={styles.subText}>IV thrombolytic in the setting of sickle cell disease may be beneficial.</Text></Text>
                <Text style={styles.subTextList}><Text style={styles.subTextUnderline}>1) Code Stroke Activation</Text> → NIHSS; Neurology Consult</Text>
                <Text style={styles.subTextList}><Text style={styles.subTextUnderline}>2) Imaging</Text> → CT Brain non contrast; CTA/CTP as indicated; Hyperacute MRI as indicated</Text>
                <Text style={styles.subTextList}><Text style={styles.subTextUnderline}>3) Labs</Text> → CBC/BMP/Reticulocyte count; Type and screen; PT/PTT; If patient unknown to system:  Sickle Cell Screen/Hgb Electropheresis </Text>
                <Text style={styles.subTextList}><Text style={styles.subTextUnderline}>4) If Acute Ischemic Stroke Suspected</Text></Text>
                <Text style={styles.subTextList2}>a. Call hematology fellow on call to discuss emergent RBC exchange</Text>
                <Text style={styles.subTextList2}>b. If Hgb {"<"}8.5, transfuse 2 units PRBC</Text>
                <Text style={styles.subTextList2}>c. Consider IV thrombolytic. Administration of thrombolytic may impact safety of catheter placement for RBC exchange.  Discuss treatment plan with stroke attending and hematology service.</Text>
            </View >
        );
    }
}

